"""weights table

Revision ID: 8e95854761c0
Revises: 4e41adea4e96
Create Date: 2018-01-23 11:47:06.727934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e95854761c0'
down_revision = '4e41adea4e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weight_timestamp'), 'weight', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weight_timestamp'), table_name='weight')
    op.drop_table('weight')
    # ### end Alembic commands ###
